import { Reward } from "../models/Reward.js";
import { ShopifySyncJob } from "../models/ShopifySyncJob.js";
import { assertNoUserErrors, shopifyAdminGraphql, validateShopifyAdminConfiguration } from "./shopify-admin.service.js";
const MAX_ATTEMPTS=Number(process.env.REWARDS_SYNC_MAX_ATTEMPTS||5),LOCK_MS=Number(process.env.REWARDS_SYNC_LOCK_MS||5*60_000);
const DEACTIVATE=`mutation RewardDiscountDeactivate($id: ID!) { discountAutomaticDeactivate(id: $id) { automaticDiscountNode { id } userErrors { field message } } }`;

export async function enqueueRewardSync(reward){const version=Number(reward.version||1);await Reward.updateOne({_id:reward._id},{$set:{"shopifySync.desiredVersion":version,"shopifySync.status":reward.enabled?"PENDING":"DISABLED","shopifySync.lastError":null}});return ShopifySyncJob.findOneAndUpdate({shop:reward.shop,idempotencyKey:`reward:${reward._id}:version:${version}`},{$setOnInsert:{shop:reward.shop,type:"REWARD_SYNC",aggregateId:reward._id,aggregateVersion:version,idempotencyKey:`reward:${reward._id}:version:${version}`,status:"PENDING",nextAttemptAt:new Date()}},{upsert:true,new:true})}
export async function retryRewardSync(shop,rewardId){const reward=await Reward.findOne({_id:rewardId,shop});if(!reward)throw Object.assign(new Error("Reward not found"),{statusCode:404});await ShopifySyncJob.updateMany({shop,aggregateId:reward._id,status:"FAILED"},{$set:{status:"SUPERSEDED",completedAt:new Date()}});reward.version+=1;reward.shopifySync.status=reward.enabled?"PENDING":"DISABLED";await reward.save();return enqueueRewardSync(reward)}
export async function wakePendingRewardSyncs(shop){const result=await ShopifySyncJob.updateMany({shop,status:"PENDING"},{$set:{nextAttemptAt:new Date()}});if(result.modifiedCount)console.log(`[Rewards Sync] woke ${result.modifiedCount} pending job(s) for ${shop}`);return result.modifiedCount}
function retryDelay(attempt){return Math.min(600000,Math.max(5000,5000*3**Math.max(0,attempt-1)))}
export function rewardFunctionConfiguration(reward){return{schemaVersion:1,rewardId:String(reward._id),rewardVersion:Number(reward.version),type:reward.type,pointsCost:Number(reward.pointsCost),discountValue:Number(reward.discountValue||0),minimumSpend:Number(reward.minimumSpend||0),productId:reward.productId||null,collectionId:reward.collectionId||null}}

// Reward records are a catalog. They must NOT create automatic Shopify discounts: doing so
// would make a reward available without a points redemption. Shopify discount objects are
// created only when a customer redeems a reward (discountCodeAppCreate). This sync step
// validates that the shop has background Admin API authorization + the rewards Function.
// It also deactivates legacy automatic discounts created by older versions of this service.
export async function syncRewardToShopify(reward){await validateShopifyAdminConfiguration(reward.shop);const legacyDiscountId=reward.shopifySync?.discountId;if(legacyDiscountId){console.log(`[Rewards Sync] deactivating legacy automatic discount for reward ${reward._id}`);const data=await shopifyAdminGraphql(reward.shop,DEACTIVATE,{id:legacyDiscountId});assertNoUserErrors(data?.discountAutomaticDeactivate)}return{discountId:null,disabled:!reward.enabled}}
async function claimOne(){const stale=new Date(Date.now()-LOCK_MS);return ShopifySyncJob.findOneAndUpdate({$or:[{status:"PENDING",nextAttemptAt:{$lte:new Date()}},{status:"PROCESSING",lockedAt:{$lte:stale}}]},{$set:{status:"PROCESSING",lockedAt:new Date()},$inc:{attempts:1}},{new:true,sort:{createdAt:1}})}
export async function processRewardSyncJobs(limit=10){let processed=0;while(processed<limit){const locked=await claimOne();if(!locked)break;console.log(`[Rewards Sync] processing ${locked.aggregateId} v${locked.aggregateVersion} for ${locked.shop} (attempt ${locked.attempts})`);const reward=await Reward.findOne({_id:locked.aggregateId,shop:locked.shop});if(!reward||Number(reward.version)!==Number(locked.aggregateVersion)||Number(reward.shopifySync?.desiredVersion||0)!==Number(locked.aggregateVersion)){await ShopifySyncJob.updateOne({_id:locked._id,status:"PROCESSING"},{$set:{status:"SUPERSEDED",completedAt:new Date()},$unset:{lockedAt:""}});console.log(`[Rewards Sync] superseded stale job ${locked._id}`);processed++;continue}try{await Reward.updateOne({_id:reward._id,version:locked.aggregateVersion},{$set:{"shopifySync.status":"SYNCING","shopifySync.lastAttemptAt":new Date()}});const result=await syncRewardToShopify(reward),current=await Reward.findById(reward._id).lean();if(!current||Number(current.version)!==Number(locked.aggregateVersion)||Number(current.shopifySync?.desiredVersion)!==Number(locked.aggregateVersion)){await ShopifySyncJob.updateOne({_id:locked._id},{$set:{status:"SUPERSEDED",completedAt:new Date()},$unset:{lockedAt:""}});processed++;continue}await Reward.updateOne({_id:reward._id,version:locked.aggregateVersion,"shopifySync.desiredVersion":locked.aggregateVersion},{$set:{"shopifySync.status":reward.enabled?"SYNCED":"DISABLED","shopifySync.syncedVersion":locked.aggregateVersion,"shopifySync.discountId":result.discountId,"shopifySync.lastSyncedAt":new Date(),"shopifySync.lastError":null}});await ShopifySyncJob.updateOne({_id:locked._id},{$set:{status:"SYNCED",completedAt:new Date(),lastError:null},$unset:{lockedAt:""}});console.log(`[Rewards Sync] ${reward.enabled?"ready":"disabled"} ${reward._id} v${locked.aggregateVersion}`)}catch(error){console.error(`[Rewards Sync] failed ${reward._id}:`,error?.message||error);const canRetry=error?.permanent!==true&&locked.attempts<MAX_ATTEMPTS,current=await Reward.findById(reward._id).lean(),stillCurrent=current&&Number(current.version)===Number(locked.aggregateVersion)&&Number(current.shopifySync?.desiredVersion)===Number(locked.aggregateVersion);if(stillCurrent)await Reward.updateOne({_id:reward._id,version:locked.aggregateVersion},{$set:{"shopifySync.status":"FAILED","shopifySync.lastError":String(error.message).slice(0,4000),"shopifySync.lastAttemptAt":new Date()}});await ShopifySyncJob.updateOne({_id:locked._id},canRetry?{$set:{status:"PENDING",lastError:String(error.message).slice(0,4000),nextAttemptAt:new Date(Date.now()+retryDelay(locked.attempts))},$unset:{lockedAt:""}}:{$set:{status:stillCurrent?"FAILED":"SUPERSEDED",lastError:String(error.message).slice(0,4000),completedAt:new Date()},$unset:{lockedAt:""}})}processed++}return processed}
