api_version = "2026-07"

[[extensions]]
name = "FreeTheRoots Rewards Discount"
handle = "ftr-rewards-discount"
type = "function"
description = "Applies one-time FreeTheRoots rewards redemption discounts"

[[extensions.targeting]]
target = "cart.lines.discounts.generate.run"
input_query = "src/cart_lines_discounts_generate_run.graphql"
export = "cart-lines-discounts-generate-run"

[[extensions.targeting]]
target = "cart.delivery-options.discounts.generate.run"
input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
export = "cart-delivery-options-discounts-generate-run"

[extensions.build]
typegen_command = "node scripts/typegen-noop.js"
path = "dist/index.wasm"
watch = [ "src/**/*.js", "src/**/*.graphql" ]
