api_version = "2026-07"

[[extensions]]
name = "Smart FBT Discount"
handle = "smart-fbt-discount"
type = "function"
description = "Discounts only qualifying Smart Frequently Bought Together cart lines"

[[extensions.targeting]]
target = "cart.lines.discounts.generate.run"
input_query = "src/cart_lines_discounts_generate_run.graphql"
export = "cart-lines-discounts-generate-run"

[extensions.build]
command = "npm run build"
path = "dist/index.wasm"
watch = [ "src/**/*.js", "src/**/*.graphql" ]
