# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "45addc9040375543ae2144ff359b41a0"
name = "freetheroot-checkout-upsell"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
automatically_update_urls_on_dev = true
