# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7b87691c62ba9da666de9e833511c508"
name = "freetheroot-checkout-upsell"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
automatically_update_urls_on_dev = true
