import mongoose from "mongoose";
import { Router } from "express";
import { adminAuth } from "../middleware/adminAuth.js";
import { RewardCustomer } from "../models/RewardCustomer.js";
import { PointsTransaction } from "../models/PointsTransaction.js";
import { EarningRule } from "../models/EarningRule.js";
import { Reward } from "../models/Reward.js";
import { Redemption } from "../models/Redemption.js";
import { RewardSettings } from "../models/RewardSettings.js";
import { ShopifySyncJob } from "../models/ShopifySyncJob.js";
import { WebhookEvent } from "../models/WebhookEvent.js";
import { AdminAuditLog } from "../models/AdminAuditLog.js";
import { applyPointsTransaction, getCustomerLedger } from "../services/rewards.service.js";
import { releaseRedemption } from "../services/redemption.service.js";
import { ensureDefaultRewardsProgram } from "../services/defaults.service.js";
import { enqueueRewardSync, retryRewardSync } from "../services/shopify-sync.service.js";
import { retryDeadWebhook } from "../services/dead-webhook-admin.service.js";
import { ADMIN_ERROR_CODES, apiError } from "../errors/api-error.js";

export const adminApi = Router();
adminApi.use(adminAuth);

function shopFrom(req) { const shop = String(req.shopifySession?.shop || "").trim().toLowerCase(); if (!shop) throw apiError(401, ADMIN_ERROR_CODES.UNAUTHENTICATED, "Unable to resolve authenticated Shopify shop."); return shop; }
function editable(body, fields) { return Object.fromEntries(fields.filter((key) => body[key] !== undefined).map((key) => [key, body[key]])); }
function positiveInteger(value, fallback, code, field, max) { if (value === undefined || value === "") return fallback; if (!/^\d+$/.test(String(value))) throw apiError(400, code, `${field} must be an integer greater than or equal to 1.`, { field }); const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed < 1 || (max && parsed > max)) throw apiError(400, code, max ? `${field} must be between 1 and ${max}.` : `${field} must be an integer greater than or equal to 1.`, { field }); return parsed; }
function validObjectId(id) { if (!mongoose.Types.ObjectId.isValid(id)) throw apiError(400, ADMIN_ERROR_CODES.INVALID_WEBHOOK_EVENT_ID, "Invalid webhook event ID.", { field: "id" }); }

adminApi.get("/webhooks/dead", async (req, res, next) => { try { const shop = shopFrom(req); const page = positiveInteger(req.query.page, 1, ADMIN_ERROR_CODES.INVALID_PAGE, "page"); const limit = positiveInteger(req.query.limit, 25, ADMIN_ERROR_CODES.INVALID_LIMIT, "limit", 100); const topic = String(req.query.topic || "").trim(); const webhookId = String(req.query.shopifyWebhookId || "").trim(); const sort = String(req.query.sort || "desc").toLowerCase(); if (sort !== "asc" && sort !== "desc") throw apiError(400, ADMIN_ERROR_CODES.INVALID_REQUEST, "sort must be asc or desc.", { field: "sort" }); const allowedTopics = new Set(["orders/paid", "refunds/create", "customers/create"]); if (topic && !allowedTopics.has(topic)) throw apiError(400, ADMIN_ERROR_CODES.INVALID_WEBHOOK_TOPIC, "Unsupported webhook topic filter.", { field: "topic" }); const filter = { shop, status: "DEAD", ...(topic ? { topic } : {}), ...(webhookId ? { webhookId } : {}) }; const [events, total] = await Promise.all([WebhookEvent.find(filter).select("-payload").sort({ deadAt: sort === "asc" ? 1 : -1, _id: -1 }).skip((page - 1) * limit).limit(limit).lean(), WebhookEvent.countDocuments(filter)]); res.json({ data: events, meta: { page, limit, total, totalPages: Math.ceil(total / limit), hasNextPage: page * limit < total, hasPreviousPage: page > 1, requestId: req.requestId } }); } catch (error) { next(error); } });
adminApi.get("/webhooks/dead/:id", async (req, res, next) => { try { validObjectId(req.params.id); const shop = shopFrom(req); const event = await WebhookEvent.findOne({ _id: req.params.id, shop, status: "DEAD" }).lean(); if (!event) throw apiError(404, ADMIN_ERROR_CODES.WEBHOOK_EVENT_NOT_FOUND, "Webhook event not found."); const audit = await AdminAuditLog.find({ shop, resourceType: "WebhookEvent", resourceId: event._id }).sort({ createdAt: -1 }).limit(100).lean(); res.json({ data: { event, audit }, meta: { requestId: req.requestId } }); } catch (error) { next(error); } });
adminApi.post("/webhooks/dead/:id/retry", async (req, res, next) => { try { validObjectId(req.params.id); const shop = shopFrom(req); const actorId = String(req.shopifySession?.subject || "shopify-admin"); const idempotencyKey = String(req.get("Idempotency-Key") || "").trim(); const result = await retryDeadWebhook({ shop, eventId: req.params.id, actorId, idempotencyKey, requestId: req.requestId }); res.status(202).json({ ...result, meta: { ...(result.meta || {}), requestId: req.requestId } }); } catch (error) { next(error); } });

adminApi.get("/session", async (req, res, next) => { try { const shop = shopFrom(req); await ensureDefaultRewardsProgram(shop); res.json({ shop, subject: req.shopifySession?.subject || "admin" }); } catch (error) { next(error); } });
adminApi.post("/seed-defaults", async (req, res, next) => { try { res.json(await ensureDefaultRewardsProgram(shopFrom(req))); } catch (error) { next(error); } });
adminApi.get("/dashboard", async (req, res, next) => { try { const shop = shopFrom(req); const [members, aggregate, recent, syncFailed, syncPending] = await Promise.all([RewardCustomer.countDocuments({ shop }), RewardCustomer.aggregate([{ $match: { shop } }, { $group: { _id: null, pointsOutstanding: { $sum: "$pointsBalance" }, pointsReserved: { $sum: "$pointsReserved" }, lifetimeEarned: { $sum: "$lifetimeEarned" }, lifetimeRedeemed: { $sum: "$lifetimeRedeemed" } } }]), PointsTransaction.find({ shop }).sort({ createdAt: -1 }).limit(10).lean(), Reward.countDocuments({ shop, "shopifySync.status": "FAILED" }), Reward.countDocuments({ shop, "shopifySync.status": { $in: ["PENDING", "SYNCING"] } })]); res.json({ members, pointsOutstanding: aggregate[0]?.pointsOutstanding || 0, pointsReserved: aggregate[0]?.pointsReserved || 0, lifetimeEarned: aggregate[0]?.lifetimeEarned || 0, lifetimeRedeemed: aggregate[0]?.lifetimeRedeemed || 0, syncFailed, syncPending, recent }); } catch (error) { next(error); } });
adminApi.get("/customers", async (req, res, next) => { try { const shop = shopFrom(req), q = String(req.query.q || "").trim(), filter = { shop }; if (q) filter.$or = ["email", "firstName", "lastName", "shopifyCustomerId"].map((key) => ({ [key]: { $regex: q, $options: "i" } })); res.json({ customers: await RewardCustomer.find(filter).sort({ updatedAt: -1 }).limit(100).lean() }); } catch (error) { next(error); } });
adminApi.get("/customers/:id", async (req, res, next) => { try { res.json(await getCustomerLedger({ shop: shopFrom(req), shopifyCustomerId: req.params.id })); } catch (error) { next(error); } });
adminApi.post("/customers/:id/adjust", async (req, res, next) => { try { const { operation, points, reason, note, customer } = req.body; if (!["ADD", "REMOVE"].includes(operation)) throw apiError(400, ADMIN_ERROR_CODES.INVALID_REQUEST, "operation must be ADD or REMOVE"); const amount = Math.abs(Number(points)); const result = await applyPointsTransaction({ shop: shopFrom(req), shopifyCustomerId: req.params.id, type: "ADJUST", points: operation === "REMOVE" ? -amount : amount, source: "ADMIN_ADJUSTMENT", reason, note, createdBy: req.shopifySession?.subject || "shopify-admin", customer, idempotencyKey: `admin:${req.params.id}:${Date.now()}:${Math.random().toString(36).slice(2)}` }); res.status(201).json(result); } catch (error) { next(error); } });
adminApi.get("/activity", async (req, res, next) => { try { res.json({ transactions: await PointsTransaction.find({ shop: shopFrom(req) }).sort({ createdAt: -1 }).limit(200).lean() }); } catch (error) { next(error); } });

adminApi.get("/redemptions", async (req, res, next) => { try { const shop = shopFrom(req); const status = String(req.query.status || "").trim().toUpperCase(); const q = String(req.query.q || "").trim(); const allowed = new Set(["RESERVED", "COMMITTED", "RELEASED", "CANCELLED", "REFUNDED"]); if (status && !allowed.has(status)) throw apiError(400, ADMIN_ERROR_CODES.INVALID_REQUEST, "Invalid redemption status filter."); const filter = { shop, ...(status ? { status } : {}) }; if (q) filter.$or = [{ shopifyCustomerId: { $regex: q, $options: "i" } }, { publicReference: { $regex: q, $options: "i" } }, { shopifyOrderId: { $regex: q, $options: "i" } }]; const redemptions = await Redemption.find(filter).select("-tokenHash").populate("rewardId", "name type pointsCost discountValue").sort({ createdAt: -1 }).limit(200).lean(); const customerIds = [...new Set(redemptions.map(r => r.shopifyCustomerId))]; const customers = await RewardCustomer.find({ shop, shopifyCustomerId: { $in: customerIds } }).select("shopifyCustomerId firstName lastName email").lean(); const byCustomer = new Map(customers.map(c => [c.shopifyCustomerId, c])); res.json({ redemptions: redemptions.map(r => ({ ...r, customer: byCustomer.get(r.shopifyCustomerId) || null })) }); } catch (error) { next(error); } });
adminApi.post("/redemptions/:reference/cancel", async (req, res, next) => { try { const shop = shopFrom(req); const reference = String(req.params.reference || "").trim(); if (!reference) throw apiError(400, ADMIN_ERROR_CODES.INVALID_REQUEST, "Redemption reference is required."); const redemption = await releaseRedemption({ shop, publicReference: reference, status: "CANCELLED" }); await AdminAuditLog.create({ shop, actorId: String(req.shopifySession?.subject || "shopify-admin"), action: "REDEMPTION_CANCELLED", resourceType: "Redemption", resourceId: redemption._id, metadata: { publicReference: reference, points: redemption.points, requestId: req.requestId } }); res.json({ redemption }); } catch (error) { next(error); } });

adminApi.get("/earning-rules", async (req, res, next) => { try { res.json({ rules: await EarningRule.find({ shop: shopFrom(req) }).sort({ priority: 1, createdAt: 1 }).lean() }); } catch (error) { next(error); } });
adminApi.post("/earning-rules", async (req, res, next) => { try { res.status(201).json({ rule: await EarningRule.create({ ...req.body, shop: shopFrom(req) }) }); } catch (error) { next(error); } });
adminApi.put("/earning-rules/:id", async (req, res, next) => { try { const updates = editable(req.body, ["name", "type", "enabled", "points", "pointsPerDollar", "multiplier", "priority", "conditions"]); const rule = await EarningRule.findOneAndUpdate({ _id: req.params.id, shop: shopFrom(req) }, { $set: updates }, { new: true, runValidators: true }).lean(); if (!rule) return res.status(404).json({ error: "Rule not found" }); res.json({ rule }); } catch (error) { next(error); } });
adminApi.delete("/earning-rules/:id", async (req, res, next) => { try { const result = await EarningRule.deleteOne({ _id: req.params.id, shop: shopFrom(req) }); res.status(result.deletedCount ? 204 : 404).end(); } catch (error) { next(error); } });
adminApi.get("/rewards", async (req, res, next) => { try { res.json({ rewards: await Reward.find({ shop: shopFrom(req) }).sort({ pointsCost: 1 }).lean() }); } catch (error) { next(error); } });
adminApi.post("/rewards", async (req, res, next) => { try { const reward = await Reward.create({ ...req.body, shop: shopFrom(req), version: 1, shopifySync: { desiredVersion: 1, syncedVersion: 0, status: "PENDING" } }); await enqueueRewardSync(reward); res.status(201).json({ reward }); } catch (error) { next(error); } });
adminApi.put("/rewards/:id", async (req, res, next) => { try { const shop = shopFrom(req), updates = editable(req.body, ["name", "type", "enabled", "pointsCost", "discountValue", "minimumSpend", "productId", "collectionId", "metadata"]); const reward = await Reward.findOneAndUpdate({ _id: req.params.id, shop }, { $set: updates, $inc: { version: 1 } }, { new: true, runValidators: true }); if (!reward) return res.status(404).json({ error: "Reward not found" }); await enqueueRewardSync(reward); res.json({ reward }); } catch (error) { next(error); } });
adminApi.delete("/rewards/:id", async (req, res, next) => { try { const reward = await Reward.findOne({ _id: req.params.id, shop: shopFrom(req) }); if (!reward) return res.status(404).end(); reward.enabled = false; reward.version += 1; await reward.save(); await enqueueRewardSync(reward); res.status(204).end(); } catch (error) { next(error); } });
adminApi.post("/rewards/:id/retry-sync", async (req, res, next) => { try { await retryRewardSync(shopFrom(req), req.params.id); res.status(202).json({ ok: true }); } catch (error) { next(error); } });
adminApi.get("/sync-jobs", async (req, res, next) => { try { res.json({ jobs: await ShopifySyncJob.find({ shop: shopFrom(req) }).sort({ createdAt: -1 }).limit(100).lean() }); } catch (error) { next(error); } });
adminApi.get("/settings", async (req, res, next) => { try { const shop = shopFrom(req), settings = await RewardSettings.findOneAndUpdate({ shop }, { $setOnInsert: { shop } }, { upsert: true, new: true }).lean(); res.json({ settings }); } catch (error) { next(error); } });
adminApi.put("/settings", async (req, res, next) => { try { const shop = shopFrom(req), updates = editable(req.body, ["pointNameSingular", "pointNamePlural", "pointsExpireEnabled", "pointsExpireAfterDays", "earnOnTaxes", "earnOnShipping", "earnOnGiftCards", "refundPolicy", "allowDiscountCombinations"]), settings = await RewardSettings.findOneAndUpdate({ shop }, { $set: updates, $setOnInsert: { shop } }, { upsert: true, new: true, runValidators: true }).lean(); res.json({ settings }); } catch (error) { next(error); } });
